theme: jekyll-theme-minimal
title: Benedict Bahr-Kalus
logo: blob/main/assets/images/White\ Blue\ Patterns\ Business\ Email\ Header.png
description: Cosmologist at the [Korea Astronomy and Space Science Institute](http://cosmology.kasi.re.kr/index.php)
