name: Update Publications
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Hier geben wir dem Job explizit Schreibrechte
      contents: write
    steps:
      - uses: actions/checkout@v4 # Update auf v4 für Node 24 Support
      - name: Set up Python
        uses: actions/setup-python@v5 # Update auf v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run update script
        env:
          ADS_API_TOKEN: ${{ secrets.ADS_API_TOKEN }}
        run: python update_pubs.py
      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add publications.json
          git commit -m "Update publication list from ADS" || exit 0
          git push
